//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lensophy.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message_pt_br {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message_pt_br() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lensophy.Domain.Resource.Message.pt-br", typeof(Message_pt_br).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analise a mensagem: `{0}`..
        /// </summary>
        internal static string AnalyseTheMessage {
            get {
                return ResourceManager.GetString("AnalyseTheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reta palavra de Buda: representa a importância de praticar a comunicação honesta, verdadeira e benevolente, que beneficie tanto quem fala quanto quem ouve. Evite falar mal ou prejudicar a reputação de alguém. Não use linguagem grosseira, insultos ou palavras que possam magoar ou infligir sofrimento emocional..
        /// </summary>
        internal static string BuddhaVirtue {
            get {
                return ResourceManager.GetString("BuddhaVirtue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O discípulo confiável de Confúcio: busca enfatizar a importância da ética nas relações interpessoais e na busca pela virtude moral. Busca fazer o que é certo em todas as situações. Cultiva virtudes como a compaixão, a honestidade e o respeito..
        /// </summary>
        internal static string ConfuciusVirtue {
            get {
                return ResourceManager.GetString("ConfuciusVirtue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Considerando o seguinte contexto: &apos;{0}&apos;..
        /// </summary>
        internal static string ConsideringFollowingContext {
            get {
                return ResourceManager.GetString("ConsideringFollowingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Considerando as seguintes virtudes:.
        /// </summary>
        internal static string ConsideringFollowingVirtues {
            get {
                return ResourceManager.GetString("ConsideringFollowingVirtues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elabore a resposta sem exceder o limite de `{0}` tokens da Api..
        /// </summary>
        internal static string DoNotExceedMaxTokens {
            get {
                return ResourceManager.GetString("DoNotExceedMaxTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reescreva a mensagem, com base nas virtudes mencionadas, sem mudar ou corromper o sentido original da mensagem, sem mencionar nenhuma das virtudes..
        /// </summary>
        internal static string RewriteMessage {
            get {
                return ResourceManager.GetString("RewriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sintetize a resposta em 20 palavras ou menos..
        /// </summary>
        internal static string SaitamaVirtue {
            get {
                return ResourceManager.GetString("SaitamaVirtue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triplo filtro de Sócrates: promover a bondade e considerar a utilidade de nossas palavras. Palavras e as ações devem ser benéficas para todos os envolvidos, promovendo o bem-estar e a harmonia. As informações devem ter um propósito construtivo e contribuir para o conhecimento ou o progresso..
        /// </summary>
        internal static string SocratesVirtue {
            get {
                return ResourceManager.GetString("SocratesVirtue", resourceCulture);
            }
        }
    }
}
