//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lensophy.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lensophy.Domain.Resource.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze the message: `{0}`..
        /// </summary>
        public static string AnalyseTheMessage {
            get {
                return ResourceManager.GetString("AnalyseTheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The straight word of Buddha: represents the importance of practicing honest, truthful, and benevolent communication that benefits both the speaker and the listener. Avoid speaking ill or harming someone&apos;s reputation. Do not use rude language, insults, or words that may hurt or inflict emotional suffering..
        /// </summary>
        public static string BuddhaVirtue {
            get {
                return ResourceManager.GetString("BuddhaVirtue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trustworthy disciple of Confucius: seeks to emphasize the importance of ethics in interpersonal relationships and the pursuit of moral virtue. Strives to do what is right in all situations and cultivates virtues such as compassion, honesty, and respect..
        /// </summary>
        public static string ConfuciusVirtue {
            get {
                return ResourceManager.GetString("ConfuciusVirtue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Considering the following context: &apos;{0}&apos;..
        /// </summary>
        public static string ConsideringFollowingContext {
            get {
                return ResourceManager.GetString("ConsideringFollowingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Considering the following virtues: the triple filter of Socrates, the righteous word of Buddha and the trustworthy disciple of Confucius.
        /// </summary>
        public static string ConsideringFollowingVirtues {
            get {
                return ResourceManager.GetString("ConsideringFollowingVirtues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop the answer without exceeding the limit of `{0}` tokens from the Api..
        /// </summary>
        public static string DoNotExceedMaxTokens {
            get {
                return ResourceManager.GetString("DoNotExceedMaxTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewrite the message based on the mentioned virtues without changing or corrupting the original meaning of the message, without mentioning any of the virtues..
        /// </summary>
        public static string RewriteMessage {
            get {
                return ResourceManager.GetString("RewriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthesize the answer in 20 words or less..
        /// </summary>
        public static string SaitamaVirtue {
            get {
                return ResourceManager.GetString("SaitamaVirtue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socrates&apos; Triple Filter: promotes kindness and considers the utility of our words. Words and actions should be beneficial to all involved, promoting well-being and harmony. Information should serve a constructive purpose and contribute to knowledge or progress..
        /// </summary>
        public static string SocratesVirtue {
            get {
                return ResourceManager.GetString("SocratesVirtue", resourceCulture);
            }
        }
    }
}
